### PR TITLE
integrate LCD

### PR DESCRIPTION
**Pull request by moinmoin-sh**
I tried to move the customized BMD-LCD lib to the sketch folder. To make the new lib active it's also required to chande the #include in RACK32-lib to point to the new lib. Unfortunately that won't compile. Libraries only except includes with the libraries, not from sketch folders. So I copies the RACK32.cpp and .h file into the sketch folder as well and made the required changes to RACK32 to interface with the new LCD lib. 

That works so far (the sketch can be compiled and shows the 9 bars as N/A on the screen)  but it's probably not what you want.

Any ideas how how to manage that?

### CODE REVIEW

**Comment by sumnerboy12** [comment]
Bugger - forgot about the Rack32 -> LCD dependency. We could try and get fancy and define some sort of LCD interface, which the core/PDU LCD libraries both implement, and pass this down to the Rack32, rather than the concrete LCD class.

The interface would contain the following;
```
    void begin(void);
    void loop(void);

    int draw_header(const char * fwShortName, const char * fwMaker, const char * fwVersion, const char * fwPlatform, const uint8_t * fwLogo = NULL);

    void trigger_mqtt_rx_led(void);
    void trigger_mqtt_tx_led(void);
    
    void show_temp(float temperature, char unit = 'C');
    void show_event(const char * s_event);
    
    void setBrightnessOn(int brightness_on);
    void setBrightnessDim(int brightness_dim);
    void setOnTimeDisplay(int ontime_display);
    void setOnTimeEvent(int ontime_event);
```

And then the I/O LCD library (our current lib) would have the extra stuff it needs;
```
    void draw_ports(int port_layout, uint8_t mcps_found);
    void process(uint8_t mcp, uint16_t io_value);
    void setPortConfig(uint8_t mcp, uint8_t pin, int config);
```

And the PDU LCD library would have its own set of specific methods.

The Rack32 lib would no longer instantiate the LCD class itself, it would need to be passed in by the calling firmware. So the firmware can decide what type of LCD to use. 

The methods below would need to move out of the Rack32 lib and up into the firmware code, since they are I/O LCD specific;
```
  _screen.draw_ports(layout, mcpCount);
  _screen.setPortConfig(mcp, pin, config);
  _screen.process(mcp, ioValue);
```

This would then allow for any type of LCD rendering logic to be implemented by the firmware, as long as it implemented the base LCD interface, so the Rack32 lib can handle the common stuff.

What do you think?

**Comment by JamesKennewell** [comment]
Is there a way we can pull a libary of sorts from the interwebs? 

Im thinking on setup on the pdu it pulls the layout for the lcd

**Comment by moinmoin-sh** [comment]
> Is there a way we can pull a libary of sorts from the interwebs?
> 
> Im thinking on setup on the pdu it pulls the layout for the lcd

This is not possible in our FW. The page as seen on the LCD is rendered with embeded code. I'm not aware of any possibilty to reload parts of the code during runtime.

**Comment by moinmoin-sh** [comment]
I got lost here. No idea how to implement such fancy interface. I thought different ways but ran allways into a dead end. The main issue I'm struggeling with is that I have different layouts for the info section (IP,MAC,MQTT,TEMP) with belongs to the common part - which means need to load different common parts. No clue how to solve this other than having different lib.

Could you explain the interface idea or try to integrate it?

btw: looks like I'm able to split the LCD-lib into COMMON and CUSTOM parts and handle that as you layout above, but no luck with differen COMMON parts.

**Comment by sumnerboy12** [comment]
Could you add some setters in the core lib to allow a custom LCD lib to control what is displayed? Something like `hideTemp(true)`, `hideMqttTopic(true)`, `hideMacAddress(true)` - these are all `false` by default and the PDU LCD lib can set the ones it needs to hide in order to make enough room?

**Comment by moinmoin-sh** [comment]
I followed your suggestion in a little different way because position changes are rquired in addition to hide/show. Thanks for pushing me into this direction.
Forget this PR and see the new one.

**Pull request closed without merging**
